# Base configs
baseurl: 
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "HAWI Studios"
subtitle: "CREATING CAPTIVATING CONTENT THROUGH SIGHT AND SOUND"
author: "HAWI Studios"
header:
 title: "HAWI"
 subtitle: "Studios"
footer:
 name: "Your window to the natural world."
 bio: "We are a small studio with a group of people who are passionate about creating meaningful and entertaining content using cameras, music, and sound effects"
 github: "Want to experience nature in 4K? Just visit our <a href=\"https://www.youtube.com/@HAWIStudios/shorts\">YouTube Channel</a> 😉"
web_design: "Harvey Wincent"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/HAWIStudios"
  instagram: "https://www.instagram.com/harveywincent"
  youtube: "https://www.youtube.com/@HAWIStudios/"
  tiktok: "https://www.tiktok.com/@hawistudios"
  snapchat: "https://www.snapchat.com/add/hawistudios"
  facebook: "https://www.facebook.com/HAWIStudios"